name: huixinapp
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dot_navigation_bar: ^1.0.1+4
  flex_color_scheme: ^6.1.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.0
  flutter_form_builder: ^7.8.0
  font_awesome_flutter: ^10.4.0
  form_builder_validators: ^8.5.0
  google_fonts: ^4.0.3
  image_picker: ^0.8.7
  just_audio: ^0.9.32
  responsive_framework: ^0.2.0

dev_dependencies:
  flutter_launcher_icons: "^0.12.0"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/foreground.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FF19A7CE"
  adaptive_icon_foreground: "assets/images/foreground.png"
  web:
    generate: true
    image_path: "assets/images/foreground.png"
    background_color: "#FF19A7CE"
    theme_color: "#FF19A7CE"
  windows:
    generate: true
    image_path: "assets/images/foreground.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/foreground.png"
