name: flutter_huixin_app
description: Learn mandarin with Huixin App and have fun!
publish_to: "none"

version: 1.0.2-test9+5

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  audio_session: ^0.1.13
  awesome_dialog: ^3.0.2
  bloc: ^8.1.1
  cached_network_image: ^3.2.3
  crypto: ^3.0.2
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  device_info_plus: ^8.1.0
  dot_navigation_bar: ^1.0.1+4
  double_back_to_close_app: ^2.1.0
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  firebase_messaging: ^14.4.0
  flex_color_scheme: ^7.0.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_bloc: ^8.1.2
  flutter_form_builder: ^7.8.0
  flutter_local_notifications: ^13.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_secure_storage: ^8.0.0
  flutter_sound: ^9.2.13
  flutter_sound_platform_interface: null
  font_awesome_flutter: ^10.4.0
  form_builder_validators: ^8.5.0
  freezed_annotation: ^2.2.0
  google_fonts: ^4.0.3
  google_sign_in: ^6.1.0
  http: ^0.13.5
  image_picker: ^0.8.7+1
  in_app_update: ^4.0.1
  intl: ^0.18.0
  just_audio: ^0.9.32
  loader_overlay: ^2.2.0
  lottie: ^2.3.2
  modal_bottom_sheet: ^3.0.0-pre
  permission_handler: ^10.2.0
  pretty_http_logger: ^0.2.1
  random_avatar: ^0.0.8
  responsive_framework: ^0.2.0
  shimmer: ^2.0.0
  sign_in_with_apple: ^4.3.0
  top_snackbar_flutter: ^3.0.0+1
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2

dependency_overrides:
  intl: ^0.18.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
    - assets/lottie/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/fleetime.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFF4546"
  adaptive_icon_foreground: "assets/images/fleetime.png"
  web:
    generate: true
    image_path: "assets/images/fleetime.png"
    background_color: "#FFFF4546"
    theme_color: "#FFFF4546"
  windows:
    generate: true
    image_path: "assets/images/fleetime.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/fleetime.png"

flutter_native_splash:
  background_image: "assets/images/background.png"
  image: "assets/images/splash_icon.png"

  android_12:
    color: "#D79F00"
    icon_background_color: "#FF4546"

  web: false
  fullscreen: true
