name: Fleetime Flutter CI/CD Configuration

# Command ini digunakan untuk mentrigger workflow ini menggunakan
# event push tag pada branch master
on:
  push:
    tags:
      - "v*.*.*" # on every version tag will build a new android artifact example: v3.1.2+6
jobs:
  build:
    #1. Build APK dan APPBUNDLE
    name: Build Artifacts and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Menyiapkan Java
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "microsoft"
          java-version: "11"

      # Menyiapkan Flutter dengan menggunakan channel stable
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.7"
          channel: "stable"

      # Step ini digunakan untuk menginstall dependency yang dibutuhkan
      - name: Pub Get Packages
        run: flutter pub get

      # Step ini digunakan untuk build apk dan split per abi
      - name: Build APK
        run: flutter build apk --split-per-abi --release

      # Step ini digunakan untuk build aab
      - name: Build APPBUNDLE
        run: flutter build appbundle --release

      # Step ini digunakan untuk merelease apk dan aab ke github release
      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.MY_TOKEN }}
          artifacts: "build/app/outputs/apk/release/*.apk,build/app/outputs/bundle/release/*.aab"

      # Step ini digunakan untuk menyimpan appbundle ke artifacts yang nantinya akan diteruskan ke step 2
      - name: Save APPBUNDLE to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: APPBUNDLE
          path: build/app/outputs/bundle/release/app-release.aab
