name: Gh-Pages

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # Only works with v2
      - uses: subosito/flutter-action@v1
      - uses: rezajax/flutter-gh-pages@v7
        with:
          baseHref: /kurikara-divincarnate/
